---
# Role configure tasks

- block:
    - name: Setup php variable
      ini_file:
        path: "{{ php_configuration_path }}"
        section: "{{ php_option.section }}"
        option: "{{ php_option.variable }}"
        value: "{{ php_option.value }}"
      loop: >-
        {{ php_ini_values | unique }}
      loop_control:
        loop_var: php_option
        label: "{{ php_option.variable }}"
  tags:
    - role::php
