---
# Role tasks
- block:
    - import_tasks: install.yml
      when: php_state == 'present'
    - import_task: configure.yml
      when:
        - php_state == 'present'
        - php_ini_values is defined
    - import_tasks: uninstall.yml
      when: php_state == 'absent'
  vars:
    php_modules_managed: >-
      {{ php_modules
         + ((php_modules_load_from_hostvars)
            | ternary(php_modules_hostvars
                      | default([])
                      | flatten,
                      [])) }}
  tags:
    - role::php
