---
# Role tasks
- block:
  
    - name: set PHP memory limit
      ini_file:
        path: "{{ php_configuration_file }}"
        section: "{{ php_option.section }}"
        option: "{{ php_option.variable }}"
        value: "{{ php_option.value }}"
      loop: >-
        {{ php_ini_values | unique }}
      loop_control:
        loop_var: php_option

  tags:
    - role::php
