---
# Role install tasks

- block:
    - name: Install remi php repository package
      yum:
        name: "{{ php_remi_repository }}"
        state: present
        disable_gpg_check: yes

    - name: Install base php packages
      yum:
        name: "{{ php_base_rpm }}"
        state: present
        enablerepo: "remi-php{{ php_version | regex_replace('\\.', '') }}"
        disable_gpg_check: "{{ php_disable_gpg_check | bool }}"
      loop: "{{ php_base_packages }}"
      loop_control:
        loop_var: php_base_rpm
      notify: httpd restart

    - name: Remove php modules
      yum:
        name: "{{ php_module_remove }}"
        state: absent
        disable_gpg_check: "{{ php_disable_gpg_check | bool }}"
      loop: >-
        {{ php_modules_managed
            | selectattr('state', 'equalto', 'absent')
            | map(attribute='name')
            | difference(php_base_packages)
            | list
            | unique }}
      loop_control:
        loop_var: php_module_remove
      notify: httpd restart

    - name: Install php modules
      yum:
        name: "{{ php_module_install }}"
        state: present
        enablerepo: "remi-php{{ php_version | regex_replace('\\.', '') }}"
        disable_gpg_check: "{{ php_disable_gpg_check | bool }}"
      loop: >-
        {{ php_modules_managed
            | selectattr('state', 'equalto', 'present')
            | map(attribute='name')
            | list
            | unique }}
      loop_control:
        loop_var: php_module_install
      notify: httpd restart

  environment: "{{ proxy_client_environment | default({}) }}"
  tags:
    - role::php
