---
# Role install tasks

- block:
    - name: Install remi php repository package
      yum:
        name: "{{ php_remi_repository }}"
        state: present
        disable_gpg_check: yes

    - when: ansible_facts.distribution_major_version is version("8", ">=")
      block:
        - name: Gather enabled dnf modules
          command: /usr/bin/dnf module list --enabled -y
          register: php_dnf_module_result
          changed_when: no

        - block:
            - name: Reset dnf php module
              command: /usr/bin/dnf module reset php -y
              changed_when: yes

            - name: Enable dnf remi php module
              command: >-
                /usr/bin/dnf module install php:remi-{{ php_version }} -y
              register: php_dnf_module_install_result
              changed_when: >-
                php_dnf_module_install_result.stdout is search("Installing")
          when: >-
            php_dnf_module_result.stdout_lines
            | select("search", "php.*remi-" ~ php_version ~ ".*\[e\]")
            | list
            | length == 0
      environment:
        LANGUAGE: en_US

    - name: Install base php packages
      yum:
        name: "{{ php_base_rpm }}"
        state: >-
          {{ (php_force_update | bool) | ternary("latest", "present") }}
        enablerepo: "remi-php{{ php_version | regex_replace('\\.', '') }}"
        disable_gpg_check: "{{ php_disable_gpg_check | bool }}"
      loop: "{{ php_base_packages }}"
      loop_control:
        loop_var: php_base_rpm
      notify: httpd restart

    - name: Remove php modules
      yum:
        name: "{{ php_module_remove }}"
        state: absent
        disable_gpg_check: "{{ php_disable_gpg_check | bool }}"
      loop: >-
        {{ php_modules_managed
            | selectattr('state', 'equalto', 'absent')
            | map(attribute='name')
            | difference(php_base_packages)
            | list
            | unique }}
      loop_control:
        loop_var: php_module_remove
      notify: httpd restart

    - name: Install php modules
      yum:
        name: "{{ php_module_install }}"
        state: >-
          {{ (php_force_update | bool) | ternary("latest", "present") }}
        enablerepo: "remi-php{{ php_version | regex_replace('\\.', '') }}"
        disable_gpg_check: "{{ php_disable_gpg_check | bool }}"
      loop: >-
        {{ php_modules_managed
            | selectattr('state', 'equalto', 'present')
            | map(attribute='name')
            | list
            | unique }}
      loop_control:
        loop_var: php_module_install
      notify: httpd restart
  environment: "{{ proxy_client_environment | default({}) }}"
  tags:
    - role::php
