---
# Role uninstall tasks

- block:
    - name: Remove remi php repository package
      yum:
        name: >-
          {{ php_remi_repository
             | urlsplit("path")
             | basename
             | regex_replace("\.rpm", "") }}
        state: absent
        disable_gpg_check: yes

    - name: Remove all php modules
      yum:
        name: >-
          {{ php_modules_managed
            | map(attribute='name')
            | list
            | unique }}
        state: absent
        disable_gpg_check: yes
      notify: httpd restart

    - name: Remove base php packages
      yum:
        name: "{{ php_base_packages }}"
        state: absent
        disable_gpg_check: yes
      notify: httpd restart
  environment: "{{ proxy_client_environment | default({}) }}"
  tags:
    - role::php
