---
# Role uninstall tasks

- block:
    - name: Remove remi php repository package
      yum:
        name: "{{ php_remi_repository }}"
        state: absent
        disable_gpg_check: yes

    - name: Remove all php modules
      yum:
        name: "{{ php_module_remove }}"
        state: absent
        disable_gpg_check: yes
      loop: >-
        {{ php_modules_managed
            | map(attribute='name')
            | list
            | unique }}
      loop_control:
        loop_var: php_module_remove
      notify: httpd restart

    - name: Remove base php packages
      yum:
        name: "{{ php_base_rpm }}"
        state: absent
        disable_gpg_check: yes
      loop: "{{ php_base_packages }}"
      loop_control:
        loop_var: php_base_rpm
      notify: httpd restart

  environment: "{{ proxy_client_environment | default({}) }}"
  tags:
    - role::php
