---

- name: Create a index.php with phpinfo
  copy:
    dest: "/var/www/html/index.php"
    content: |
      <?php
        phpinfo();
      ?>

- name: Check that apache is listening
  wait_for:
    port: 80
    timeout: 10
