---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
    requirements-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:centos7
    dockerfile: ../resources/Dockerfile.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ~/srv/ansible/roles
  playbooks:
    converge: ../resources/converge.yml
    cleanup: ../resources/cleanup.yml
    side_effect: ../resources/side_effect.yml
  inventory:
    group_vars:
      molecule_hosts:
        php_state: absent
verifier:
  name: ansible
