---

- name: Prepare
  hosts: molecule_hosts
  gather_facts: no
  roles:
    - role: amtega.apache
      vars:
        apache_modules: []

    - role: amtega.php
      vars:
        php_version: 7.3
        php_force_update: no
  tasks:
    - name: Create a index.php with phpinfo
      copy:
        dest: "/var/www/html/index.php"
        content: |
          <?php
            phpinfo();
          ?>
        mode: 0644

    - name: Check that apache is listening
      wait_for:
        port: 80
        timeout: 10
