---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
    requirements-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:centos7
    dockerfile: ../resources/Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:stream8
    dockerfile: ../resources/Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
    cleanup: ../resources/cleanup.yml
    side_effect: ../resources/side_effect.yml
    verify: ../resources/verify.yml
  inventory:
    hosts:
      molecule_hosts:
        vars:
          php_version: 8.1
          php_ini_values:
            - variable: short_open_tag
              state: absent
            - variable: max_execution_time
              state: present
              value: 60
              section: PHP
            - variable: memory_limit
              state: present
              value: 256M
              section: PHP
            - variable: post_max_size
              state: present
              value: 22M
              section: PHP
            - variable: upload_max_filesize
              state: present
              value: 20M
              section: PHP
            - variable: date.timezone
              state: present
              value: Europe/Madrid
              section: Date
          php_modules_testhostvars:
            - name: php-mysqlnd
              state: present
            - name: php-gd
              state: present
            - name: php-mbstring
              state: present
            - name: php-intl
              state: present
            - name: php-pecl-apcu
              state: present
            - name: php-opcache
              state: present
verifier:
  name: ansible
